### ISSUE TITLE
Form to complete prior to workshop starting 

### ISSUE THREAD

**Issue by AliciateagleSR2** [codebar/chapter-organiser-meetings#62]
This may be a bit fluffy as a subject but I saw W/L sending around a google form or similar (I can't remember exactly what it was) to all students before they kicked off pairing and I haven't ever done this so need to check if I have missed something

**Comment by brunogirin** [comment]
London are the only ones doing that. We (West London) never do it, we rely on what the students and coaches enter when they register. London tend to have more advanced processes than the rest of us because they are the largest chapter with the largest number of students, coaches and organisers.

One thing that London do which I quite like is that they send a Google form for feedback *after* the workshop. We don't do it either because we never got round to sorting it out!

**Comment by KimberleyCook** [comment]
@AliciateagleSR2 is there an update on this ticket/can I close it?

**Comment by AliciateagleSR2** [comment]
Morning,

Feel free to close 😊

Thanks

Alicia
Co-Founder

Recruiting for companies doing good ❤
Founder of Women Rock<https://www.sr2rec.co.uk/womenrock/> & Tech Volunteers<https://technologyvolunteers.org/>
Organiser of Codebar Bristol @codebarbristol
[A picture containing text  Description automatically generated]    [Shape  Description automatically generated with low confidence]    ***@***.***
Winner of ‘Best New Agency’ at the Recruiter Awards 2020

***@***.***

Winner of Rising Star at the Business Leader Awards 2019

We will donate £250 to a charity of your choice for every successful referral - click here<https://www.sr2rec.co.uk/referrals/> to make a difference.

SR2, Runway East, 1 Victoria Street, Bristol, BS1 6AA.
T: 0117  363 7402
M: 07891052618
www.sr2rec.co.uk<http://www.sr2rec.co.uk/>

Please register with us here.<https://www.sr2rec.co.uk/register>

 ***@***.*** <https://www.linkedin.com/company/27022839/>    ***@***.*** <https://twitter.com/SR2RECLTD>    ***@***.*** <https://www.instagram.com/sr2recltd/>

If you wish to unsubscribe please email ***@***.******@***.***>
